language: node_js
node_js: "node"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm i -g npm@^3
  - pip install --user awscli
script:
  - npm test
  - npm run build
deploy:
- provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: www-$TRAVIS_BUILD_NUMBER.ghostred.com
  local-dir: dist
  skip_cleanup: true
  on:
    branch: master
